# permissions for end users to view deployobjects.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: deployobject-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: apps
    app.kubernetes.io/part-of: apps
    app.kubernetes.io/managed-by: kustomize
  name: deployobject-viewer-role
rules:
- apiGroups:
  - app.kubebuilder.io
  resources:
  - deployobjects
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - app.kubebuilder.io
  resources:
  - deployobjects/status
  verbs:
  - get
